### ISSUE TITLE
did this die?

### ISSUE THREAD

**Issue by buddylindsey** [sleepypikachu/dad-hackers.club#1]
Was looking forward to this, but was curious if this is going to happen?

**Comment by sleepypikachu** [comment]
Been swamped, I hope so. I think the basic plan is going to be a jekyll generated static site

**Comment by buddylindsey** [comment]
okay. Was curious. I don't have the design chops to be sure, and too am swamped.

**Comment by sleepypikachu** [comment]
Having some issues with custom dns + gh-pages but I think once the dns propagates we should be good

**Comment by sleepypikachu** [comment]
Live!
